server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/testdb}
    username: postgres
    password: $$maX0000

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    database: postgresql

